apiVersion: v1
kind: Secret
metadata:
  name: {{ include "install.tokenSecretName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ include "install.serviceAccountName" . }}
type: kubernetes.io/service-account-token
