apiVersion: mogdb.enmotech.io/v1
kind: MogdbBackup
metadata:
  name: cluster1-backup
spec:
  clusterName: cluster1
  image: swr.cn-north-4.myhuaweicloud.com/mogdb-cloud/mogdb-remoteclient:2.0.1
  baseBackup:
    name: "baseBackup"
    backupLevel: full
    fileName: cluster1-backup.xbackup.gz