apiVersion: mogdb.enmotech.io/v1
kind: MogdbCluster
metadata:
  name: mogdb-cluster
  namespace: mogdb-operator-system
spec:
  podSpec:
    imagePullSecrets:
      - name: mogdb-operator-huawei-registry