apiVersion: mogdb.enmotech.io/v1
kind: MultiCluster
metadata:
  name: multi-cluster
  namespace: mogdb-operator-system
spec:
  dataCenters:
    - name: dc1
      namespace: data-plane1
      region: "dc1"
      dataCenterRole: primary
      kubeContextName: "data-plane1"
    - name: dc2
      namespace: data-plane2
      region: "dc2"
      dataCenterRole: standby
      kubeContextName: "data-plane2"