apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "install.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
  name: {{ include "install.huaweiRegistrySecretName" . }}
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImVXRmlhVzVxYVRwS1dVSkFNREEzUUdwNVlnPT0iCgkJfSwKCQkic3dyLmNuLW5vcnRoLTQubXlodWF3ZWljbG91ZC5jb20iOiB7CgkJCSJhdXRoIjogIlkyNHRibTl5ZEdndE5FQkRTRmROUTBkYU5GY3dSME0xU0VwV1FrZEhVRHBoTXpBMk1HWTRNMlZqTlRNME16WmtNMkkxTXpJNE16TmhNRFV3WVdNeFlqWTVOVFpsT1RkbU9EY3hOelV5WldNeU4ySXpaVEZsWW1aaU5UUXlaV1UxIgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson