apiVersion: rbac.authorization.k8s.io/v1
kind: {{ include "install.roleKind" . }}
metadata:
  name: {{ include "install.roleName" . }}
rules:
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - kubeclientconfigs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - mogdbclusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - mogdbclusters/finalizers
    verbs:
      - update
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - mogdbclusters/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - mogdbclustertemplates
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - mogdbdatabases
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - mogdbdatabases/finalizers
    verbs:
      - update
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - mogdbdatabases/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - mogdbpodtemplates
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - mogdbtables
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - mogdbtables/finalizers
    verbs:
      - update
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - mogdbtables/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - mogdbusers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - mogdbusers/finalizers
    verbs:
      - update
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - mogdbusers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - multiclusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - multiclusters/finalizers
    verbs:
      - update
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - multiclusters/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - multidatabases
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - multidatabases/finalizers
    verbs:
      - update
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - multidatabases/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - multitables
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - multitables/finalizers
    verbs:
      - update
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - multitables/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - multiusers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - multiusers/finalizers
    verbs:
      - update
  - apiGroups:
      - mogdb.enmotech.io
    resources:
      - multiusers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - roles
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
