apiVersion: mogdb.enmotech.io/v1
kind: MogdbCluster
metadata:
  name: cluster1
  namespace: mogdb-operator-system
spec:
  # Add fields here
  podSpec:
    volumeSpec:
      persistentVolumeClaim:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi
    backupVolumeSpec:
      persistentVolumeClaim:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi
    initImage: swr.cn-north-4.myhuaweicloud.com/mogdb-cloud/mogdb-init:3.0.3
    image: swr.cn-north-4.myhuaweicloud.com/mogdb-cloud/mogdb:3.0.3
    exporterImage: swr.cn-north-4.myhuaweicloud.com/mogdb-cloud/mogdb-exporter:3.0.3
  readPort: 30012
  writePort: 30013
  replicas: 2
  enableHa: true
