apiVersion: mogdb.enmotech.io/v1
kind: MogdbCluster
metadata:
  name: mogdb-cluster
  namespace: mogdb-operator-system
spec:
  replicas: 2
  readPort: 30012
  writePort: 30013
  ha:
    scope: mogdb-cluster
    url: http://mogdb-ha.mogdb-ha.svc.cluster.local:6544
  podSpec:
    volumeSpec:
      persistentVolumeClaim:
        accessModes:
          - ReadWriteOnce
        storageClassName: default
        resources:
          requests:
            storage: 1Gi
    backupVolumeSpec:
      persistentVolumeClaim:
        accessModes:
          - ReadWriteOnce
        storageClassName: default
        resources:
          requests:
            storage: 1Gi
    imagePullPolicy: IfNotPresent
    image: swr.cn-north-4.myhuaweicloud.com/mogdb-cloud/mogdb:3.0.4
    initImage: swr.cn-north-4.myhuaweicloud.com/mogdb-cloud/mogdb:3.0.4
    exporterImage: swr.cn-north-4.myhuaweicloud.com/mogdb-cloud/mogdb-exporter:3.1.0
