apiVersion: mogdb.enmotech.io/v1
kind: MultiCluster
metadata:
  name: mogdb-cluster
  namespace: mogdb-operator-system
spec:
  dataCenters:
    - name: dc1
      namespace: mogdb-operator-system
      region: "dc1"
      dataCenterRole: primary
      kubeContextName: "data-plane1"
      dataCenterSpec:
        podSpec:
          imagePullSecrets:
            - name: mogdb-operator-huawei-registry
    - name: dc2
      namespace: mogdb-operator-system
      region: "dc2"
      dataCenterRole: standby
      kubeContextName: "data-plane2"
      dataCenterSpec:
        podSpec:
          imagePullSecrets:
            - name: mogdb-operator-huawei-registry
