kind: Service
apiVersion: v1
metadata:
  name: {{ include "install.serviceName" . }}
  labels:
    {{- include "install.labels" . | indent 4 }}
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.annotations }}
  annotations:
  {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: api
      protocol: TCP
      port: {{ .Values.apiPort }}
      targetPort: {{ .Values.apiPort }}
  selector:
    {{- include "install.labels" . | indent 4 }}
  type: ClusterIP
  sessionAffinity: None
