# Default values for mogdb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replica: 2

mogdb:
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi
  volume:
    dataVolumeSize: 1Gi
    backupVolumeSize: 1Gi
    storageClass: default

service:
  readPort: 30012
  writePort: 30013

ha:
  scope: default
  url: http://mogdb-ha.mogdb-ha.svc.cluster.local:6544

images:
  imagePullPolicy: IfNotPresent
  initImage: swr.cn-north-4.myhuaweicloud.com/mogdb/mogdb:5.0.0
  mogdbImage: swr.cn-north-4.myhuaweicloud.com/mogdb-cloud/init:5.0.0
  exporterImage: swr.cn-north-4.myhuaweicloud.com/mogdb-cloud/mogdb-exporter:3.1.0


backup: {}
#backup:
#  auto:
#    name: "auto"
#    backupSchedules:
#      full: "*/1 * * * *"
#    storageProvider:
#      rcloneStorage:
#        name: s3-remote
#        directory: backup
#    backupType: basebackup
#    backupFileHistoryLimit: 7
#    failedJobsHistoryLimit: 7
#    successfulJobsHistoryLimit: 7
#  image: swr.cn-north-4.myhuaweicloud.com/mogdb-cloud/remote-client:3.0.0

restore: {}
#restore:
#  restoreId: "001"
#  dataSource:
#    type: "object"
#    backupType: dumpall
#    clusterName: mogdb-cluster
#    storageProvider:
#      rcloneStorage:
#        name: s3-remote
#        directory: backup
#    target: dumpall-2023-05-15-08-56-21.tar.gz
#  image: swr.cn-north-4.myhuaweicloud.com/mogdb-cloud/remote-client:3.0.0


