namespace: mogdb-operator-system

resources:
  - cluster-role-bindings.yaml
  - cluster-roles.yaml
  - deployment.yaml
  - mgorole.yaml
  - mgouser.yaml
  - service.yaml
  - service-accounts.yaml

images:
  - name: apiserver
    newName: swr.cn-north-4.myhuaweicloud.com/mogdb-cloud/mogdb-apiserver
    newTag: 2.0.1

vars:
  - name: NAMESPACE
    objref:
      kind: Namespace
      name: system
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
