apiVersion: mogdb.enmotech.io/v1
kind: MogdbCluster
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "install.labels" . | indent 4 }}
  {{- if .Values.annotations }}
  annotations:
  {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replica }}
  readPort: {{ .Values.service.readPort }}
  writePort: {{ .Values.service.writePort }}
  ha:
    url: {{ .Values.ha.url }}
    scope: {{ .Values.ha.scope }}
  podSpec:
    volumeSpec:
      persistentVolumeClaim:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.mogdb.volume.dataVolumeSize }}
        storageClassName: {{ .Values.mogdb.volume.storageClass }}
    backupVolumeSpec:
      persistentVolumeClaim:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.mogdb.volume.backupVolumeSize }}
        storageClassName: {{ .Values.mogdb.volume.storageClass }}
    {{- if .Values.imagePullSecretNames }}
    imagePullSecrets:
    {{- range .Values.imagePullSecretNames }}
      - name: {{ . | quote }}
    {{- end }}{{/* range */}}
    {{- end }}{{/* define */}}
    image: {{ .Values.images.mogdbImage }}
    initImage: {{ .Values.images.initImage }}
    exporterImage: {{ .Values.images.exporterImage }}
    imagePullPolicy: {{ .Values.images.imagePullPolicy }}
    {{- if .Values.mogdb.resources }}
    resources:
    {{- toYaml .Values.mogdb.resources | nindent 6 }}
    {{- end }}
  {{- if .Values.backup }}
  backup:
  {{- toYaml .Values.backup | nindent 4 }}
  {{- end }}
  {{- if .Values.restore }}
  restore:
  {{- toYaml .Values.restore | nindent 4 }}
  {{- end }}