# Default values for mogdb-operator-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# customize defination labels.
labels: {}
# customize defination annotations.
annotations: {}

# to enable/disable helm install multi-operator with CRD.
withCRD: false

# to enable/disable namespace model to install multi-operator.
singleNamespace: false

# to enable/disable multi-operator debug mod.
debug: true

# to enable/disable multi-operator webhook mod.
webhookPort: 9443
enableWebhook: false

# to enable/disable multi-operator control-plane env.
enableControl: true

# to enable/disable multi-operator leader election mod.
enableLeaderElection: true
leaderElectionID: 029c71aa.enmotech.io

# to enable/disable enablePrometheusMonitor.
enablePrometheusMonitor: true

# imagePullSecrets is a list of references to secrets for pulling any images.
imagePullSecrets: {}
# the name of imagePullSecrets.
imagePullSecretNames: []

# specify config for operator container
operator:
  resources:
    # Limits describes the maximum amount of compute resources allowed.
    limits:
      cpu: 500m
      memory: 500Mi
    # Requests describes the minimum amount of compute resources required.
    requests:
      cpu: 500m
      memory: 500Mi
  # PullPolicy describes a policy for if/when to pull a container image.
  imagePullPolicy: IfNotPresent
  # container image name.
  image: swr.cn-north-4.myhuaweicloud.com/mogdb-cloud/multi-operator:3.0.0
