namespace: mogdb-operator-system

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ../../bases
  - cm_rclone.yaml


patchesStrategicMerge:
  - patches/restore_base_by_time.yaml
  # - patches/restore_base_by_object.yaml
  # - patches/restore_dumpall_by_time.yaml
  # - patches/restore_dumpall_by_object.yaml
  - patches/image_pull_secret_names.yaml
