apiVersion: mogdb.enmotech.io/v1
kind: MogdbCluster
metadata:
  name: mogdb-cluster
  namespace: mogdb-operator-system
spec:
  restore:
    restoreId: "001"
    dataSource:
      type: "object"
      backupType: dumpall
      clusterName: mogdb-cluster
      storageProvider:
        rcloneStorage:
          name: s3-remote
          directory: backup
      target: dumpall-2023-05-15-08-56-21.tar.gz
    image: swr.cn-north-4.myhuaweicloud.com/mogdb-cloud/remote-client:3.0.0
