# Default values for mogdb-monitor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# customize defination labels.
labels: {}
# customize defination annotations.   
annotations: {}

image:
  pullPolicy: IfNotPresent # 镜像拉取策略
  kubeStateMetricsRepository: k8s.gcr.io/kube-state-metrics/kube-state-metrics # kube-state-metrics 镜像仓库
  kubeStateMetricsTag: 2.4.2 # kube-state-metrics 仓库镜像版本号
  alertmanagerRepository: prom/alertmanager # alertmanager 镜像仓库
  alertmanagerTag: 0.17.0 # alertmanager 仓库镜像版本号

grafanaNodeport: 41043 # grafana 图形界面地址端口
prometheusNodeport: 41042 # prometheus 图形界面地址端口
alertmanagerNodeport: 41044 # alertmanager 图形界面地址端口

# 邮箱预警配置
alertEmailHost: smtp.163.com # 告警邮箱server host
alertEmailSmtp: smtp.163.com:25 # 发送邮件的SMTP server，包括端口号
alertEmailUsername: xxxx@163.com # 发送告警的邮箱
alertEmailPassword: <邮箱密码> # 邮箱授权密码

receiversEmail: xxx@qq.com  # 接收报警的邮箱，多个用逗号隔开