apiVersion: mogdb.enmotech.io/v1
kind: MultiCluster
metadata:
  name: multi-cluster
  namespace: mogdb-operator-system
spec:
  template:
    replicas: 2
    readPort: 30012
    writePort: 30013
    ha:
      scope: mogdb-cluster
      url: http://mogdb-ha.mogdb-ha.svc.cluster.local:6544
    podSpec:
      volumeSpec:
        persistentVolumeClaim:
          accessModes:
            - ReadWriteOnce
          storageClassName: default
          resources:
            requests:
              storage: 1Gi
      backupVolumeSpec:
        persistentVolumeClaim:
          accessModes:
            - ReadWriteOnce
          storageClassName: default
          resources:
            requests:
              storage: 1Gi
      imagePullPolicy: IfNotPresent
      image: swr.cn-north-4.myhuaweicloud.com/mogdb/mogdb:5.0.0
      initImage: swr.cn-north-4.myhuaweicloud.com/mogdb-cloud/init:5.0.0
      exporterImage: swr.cn-north-4.myhuaweicloud.com/mogdb-cloud/mogdb-exporter:3.1.0
