namespace: mogdb-operator-system

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ../../bases

patchesStrategicMerge:
  - patches/datacenters.yaml
  - patches/image_pull_secret_names.yaml
