namespace: mogdb-operator-system

generatorOptions:
  disableNameSuffixHash: true

resources:
  - cm_rclone.yaml
  - ../../bases/mogdb_cluster.yaml


patchesStrategicMerge:
  # - patches/backup_auto_base.yaml
  # - patches/backup_auto_dumpall.yaml
  # - patches/backup_manual_base.yaml
  - patches/backup_manual_dumpall.yaml
  - patches/image_pull_secret_names.yaml
