apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-config
data:
  rclone.conf: |
    [s3-remote]
    type=s3
    provider=Minio
    endpoint=http://172.23.1.154:9000
    access_key_id=root
    secret_access_key=root@123
