# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
  - mogdb.enmotech.io_mogdbclusters.yaml
  - mogdb.enmotech.io_mogdbusers.yaml
  - mogdb.enmotech.io_mogdbtables.yaml
  - mogdb.enmotech.io_mogdbdatabases.yaml
  - mogdb.enmotech.io_mogdbpodtemplates.yaml
  - mogdb.enmotech.io_mogdbclustertemplates.yaml
  #+kubebuilder:scaffold:crdkustomizeresource
